parameters: {}
environment:
  APP_SECRET: '${APP_SECRET}'
  DATABASE_URL: '${DATABASE_URL}'
packages:
  - name: api
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: rrpaymentupdate
        binary: false
        main: 'index.js'
        runtime: 'nodejs:18'
        web: true
        webSecure: false
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
