parameters: {}
environment:
  APP_SECRET: '${APP_SECRET}'
  DATABASE_URL: '${DATABASE_URL}'
packages:
  - name: api
    shared: false
    environment: {}
    parameters: {}
    annotations: {}
    functions:
      - name: rrupdatepayment
        binary: false
        main: 'rrupdatepayment.main'
        runtime: 'nodejs:22'
        web: true
        webSecure: '${APP_SECRET}'
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
